<?php

/**
 *
 * image-field-no-alt - decorative - filter:no edit:no
 * image-field-alt-no-edit - filter:yes edit:no
 * image-with-image-alt - filter:yes edit:yes
 * image-field-with-background-image-alt - filter:yes edit:yes
 * image-field-with-title-label - filter:yes (should never happen) edit:no
 *
 * filter: PARSE_STRINGS::BLC_EMPTY_ALT
 *
 */

\defined('_JEXEC') or die;
return [
  'map' => [
    'cluster_icon_1' => 'image-field-no-alt',
    'cluster_icon_2' => 'image-field-no-alt',
    'cluster_icon_3' => 'image-field-no-alt',
    'content'        => 'skip',
    'marker_icon'    => 'image-field-no-alt',
    'show_content'   => 'skip',
    'show_image'     => 'skip',
    'show_link'      => 'skip',
    'show_meta'      => 'skip',
    'show_title'     => 'skip',
  ],
  'accordion' => [
    'content'    => 'skip',
    'show_image' => 'skip',
    'show_link'  => 'skip',
  ],
  'html' => [
    'content' => 'html',
  ],
  'fragment' => [
    'content' => 'skip',
  ],
  'countdown' => [
    'date'          => 'skip',
    'label_days'    => 'skip',
    'label_hours'   => 'skip',
    'label_minutes' => 'skip',
    'label_seconds' => 'skip',
    'show_label'    => 'skip',
  ],
  'totop' => [
    'link_title' => 'skip',
    'title'      => 'skip',
  ],
  'button' => [
    'content' => 'skip',
  ],
  'gallery' => [
    'content'          => 'skip',
    'show_content'     => 'skip',
    'show_hover_image' => 'skip',
    'show_hover_video' => 'skip',
    'show_link'        => 'skip',
    'show_meta'        => 'skip',
    'show_title'       => 'skip',
  ],
  'grid' => [
    'content'          => 'skip',
    'show_content'     => 'skip',
    'show_hover_image' => 'skip',
    'show_hover_video' => 'skip',
    'show_image'       => 'skip',
    'show_link'        => 'skip',
    'show_meta'        => 'skip',
    'show_title'       => 'skip',
    'show_video'       => 'skip',
  ],
  'list' => [
    'content'    => 'skip',
    'show_image' => 'skip',
    'show_link'  => 'skip',
  ],
  'nav' => [
    'content'    => 'skip',
    'show_image' => 'skip',
    'show_meta'  => 'skip',
  ],
  'overlay-slider' => [
    'content'          => 'skip',
    'show_content'     => 'skip',
    'show_hover_image' => 'skip',
    'show_hover_video' => 'skip',
    'show_link'        => 'skip',
    'show_meta'        => 'skip',
    'show_title'       => 'skip',
  ],
  'panel-slider' => [
    'content'          => 'skip',
    'show_content'     => 'skip',
    'show_hover_image' => 'skip',
    'show_hover_video' => 'skip',
    'show_image'       => 'skip',
    'show_link'        => 'skip',
    'show_meta'        => 'skip',
    'show_title'       => 'skip',
    'show_video'       => 'skip',
  ],
  'popover' => [
    'background_image'     => 'image-field-with-background-image-alt',
    'background_image_alt' => 'skip',
    'content'              => 'skip',
    'image'                => 'image-with-image-alt',
    'image_alt'            => 'skip',
    'show_content'         => 'skip',
    'show_image'           => 'skip',
    'show_link'            => 'skip',
    'show_meta'            => 'skip',
    'show_title'           => 'skip',
  ],
  'text' => [
    'content' => 'html',
  ],
  'description_list' => [
    'content'      => 'html',
    'show_content' => 'skip',
    'show_link'    => 'skip',
    'show_meta'    => 'skip',
    'show_title'   => 'skip',
  ],
  'content' => [
    'content' => 'html',
  ],
  'table' => [
    'content'      => 'skip',
    'show_content' => 'skip',
    'show_image'   => 'skip',
    'show_link'    => 'skip',
    'show_meta'    => 'skip',
    'show_title'   => 'skip',
  ],
  'social' => [
    'content' => 'skip',
  ],
  'subnav' => [
    'content' => 'skip',
  ],
  'slideshow' => [
    'content'        => 'skip',
    'link'           => 'link-with-no-anchor',
    'show_content'   => 'skip',
    'show_link'      => 'skip',
    'show_meta'      => 'skip',
    'show_thumbnail' => 'skip',
    'show_title'     => 'skip',
  ],
  'icon' => [
    'icon'            => 'skip',
    'link'            => 'link-with-icon',
    'link_aria_label' => 'skip',
    'link_target'     => 'skip',
  ],
  'quotation' => [
    'author'      => 'skip',
    'content'     => 'html',
    'footer'      => 'skip',
    'link'        => 'link-with-author',
    'link_target' => 'skip',
  ],
  'description_list_item' => [
    'content'     => 'html',
    'footer'      => 'skip',
    'link'        => 'link-with-content',
    'link_target' => 'skip',
    'meta'        => 'skip',
    'title'       => 'skip',
  ],
  'list_item' => [
    'content'     => 'html',
    'icon'        => 'skip',
    'image'       => 'image-with-image-alt',
    'image_alt'   => 'skip',
    'link'        => 'link-with-content',
    'link_target' => 'skip',
    'title'       => 'skip',
  ],
  'slideshow_item' => [
    '_media'          => 'skip',
    'content'         => 'html',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_text'       => 'skip',
    'meta'            => 'skip',
    'thumbnail'       => 'image-field-alt-no-edit',
    'title'           => 'skip',
    'video'           => 'video-with-no-title',
  ],
  'accordion_item' => [
    '_media'          => 'skip',
    'content'         => 'html',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_text'       => 'skip',

    'title' => 'skip',
    'video' => 'video-with-no-title',
  ],
  'column' => [
    '_media'      => 'skip',
    'image'       => 'image-field-no-alt',
    'video'       => 'video-with-video-title',
    'video_title' => 'skip',
  ],
  'gallery_item' => [
    '_media'          => 'skip',
    'content'         => 'html',
    'hover_image'     => 'image-field-no-alt',
    'hover_video'     => 'video-with-no-title',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_text'       => 'skip',
    'meta'            => 'skip',
    'tags'            => 'skip',

    'title'       => 'skip',
    'video'       => 'video-with-title',
    'video_title' => 'skip',
  ],
  'grid_item' => [
    'content'         => 'html',
    'hover_image'     => 'image-field-no-alt',
    'hover_video'     => 'video-with-no-title',
    'icon'            => 'skip',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_text'       => 'skip',
    'meta'            => 'skip',
    'tags'            => 'skip',

    'title' => 'skip',
    'video' => 'video-with-no-title',
  ],
  'panel' => [
    'content'         => 'html',
    'hover_image'     => 'image-field-no-alt',
    'hover_video'     => 'video-with-no-title',
    'icon'            => 'skip',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_target'     => 'skip',
    'link_text'       => 'skip',
    'meta'            => 'skip',
    'title'           => 'skip',
    'video'           => 'video-with-no-title',
  ],
  'overlay-slider_item' => [
    '_media'          => 'skip',
    'content'         => 'html',
    'hover_image'     => 'image-field-no-alt',
    'hover_video'     => 'video-with-no-title',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_text'       => 'skip',
    'meta'            => 'skip',

    'title'       => 'skip',
    'video'       => 'video-with-video-title',
    'video_title' => 'skip',
  ],
  'button_item' => [
    'content'         => 'skip',
    'dialog'          => 'html',
    'icon'            => 'skip',
    'link'            => 'link-with-link-title',
    'link_aria_label' => 'skip',
    'link_title'      => 'skip',
  ],
  'code' => [
    'content' => 'skip',
  ],
  'alert' => [
    'content'     => 'html',
    'link'        => 'link-with-title-content',
    'link_target' => 'skip',
    'title'       => 'skip',
  ],
  'overlay' => [
    '_media'          => 'skip',
    'content'         => 'html',
    'hover_image'     => 'image-field-no-alt',
    'hover_video'     => 'video-with-no-title',
    'icon'            => 'skip',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_target'     => 'skip',
    'link_text'       => 'skip',
    'meta'            => 'skip',

    'title'       => 'skip',
    'video'       => 'video-with-video-title',
    'video_title' => 'skip',
  ],
  'panel-slider_item' => [
    '_media'          => 'skip',
    'content'         => 'html',
    'hover_image'     => 'image-field-no-alt',
    'hover_video'     => 'video-with-no-title',
    'icon'            => 'skip',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_text'       => 'skip',
    'meta'            => 'skip',
    'title'           => 'skip',
    'video'           => 'video-with-no-title',
  ],
  'switcher' => [
    'content'        => 'skip',
    'show_content'   => 'skip',
    'show_image'     => 'skip',
    'show_label'     => 'skip',
    'show_link'      => 'skip',
    'show_meta'      => 'skip',
    'show_thumbnail' => 'skip',
    'show_title'     => 'skip',
  ],
  'section' => [
    '_media'      => 'skip',
    'image'       => 'image-field-no-alt',
    'title'       => 'skip',
    'video'       => 'video-with-video-title',
    'video_title' => 'skip',
  ],
  'social_item' => [
    'icon'            => 'skip',
    'image'           => 'image-field-no-alt',
    'link'            => 'link-with-icon-or-image-or-aria',
    'link_aria_label' => 'skip',
  ],
  'image' => [
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-image',
    'link_aria_label' => 'skip',
  ],
  'headline' => [
    'content'     => 'html',
    'link'        => 'link-with-content',
    'link_target' => 'skip',
  ],
  'nav_item' => [
    'content'     => 'plain',
    'icon'        => 'skip',
    'image'       => 'image-with-image-alt',
    'image_alt'   => 'skip',
    'link'        => 'link-with-content',
    'link_target' => 'skip',
    'meta'        => 'skip',
  ],
  'map_item' => [
    'content'         => 'html',
    'icon'            => 'skip',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_text'       => 'skip',
    'location'        => 'skip',
    'marker_icon'     => 'skip',
    'meta'            => 'skip',
    'title'           => 'skip',
  ],
  'subnav_item' => [
    'active'      => 'skip',
    'content'     => 'plain',
    'link'        => 'link-with-content',
    'link_target' => 'skip',
  ],
  'popover_item' => [
    'content'         => 'html',
    'image'           => 'image-with-image-alt',
    'image_alt'       => 'skip',
    'link'            => 'link-with-link-text',
    'link_aria_label' => 'skip',
    'link_text'       => 'skip',
    'meta'            => 'skip',
    'title'           => 'skip',
  ],
  'table_item' => [
    'content'   => 'html',
    'image'     => 'image-with-image-alt',
    'image_alt' => 'skip',
    'link'      => 'link-with-link-text',
    'link_text' => 'skip',
    'meta'      => 'skip',
    'title'     => 'skip',
  ],
  'switcher_item' => [
    'content'   => 'html',
    'image'     => 'image-with-image-alt',
    'image_alt' => 'skip',
    'label'     => 'skip',
    'link'      => 'link-with-link-text',
    'link_text' => 'skip',
    'meta'      => 'skip',
    'thumbnail' => 'image-field-with-title-label',
    'title'     => 'skip',
  ],
  'video' => [
    'video'             => 'video-with-video-title',
    'video_autoplay'    => 'skip',
    'video_controls'    => 'skip',
    'video_lazyload'    => 'skip',
    'video_loop'        => 'skip',
    'video_muted'       => 'skip',
    'video_playsinline' => 'skip',
    'video_poster'      => 'image-field-no-alt',
    'video_title'       => 'skip',
  ],
];
